import Head from 'next/head'
import Calculator from '../components/Calculator'
import Page from '../components/Page'

export default function Home() {
  return (
    <Page>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Calculator />
    </Page>
  )
}
